
redis:
  commonConfiguration: |-
    maxmemory 300mb
    maxmemory-policy allkeys-lru

  master:
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
    persistence:
      size: "10Gi"
