
redis:
  commonConfiguration: |-
    maxmemory 3gb
    maxmemory-policy allkeys-lru

  master:
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: 1
        memory: "2Gi"
    persistence:
      size: "10Gi"
