global:
  image:
    tag: latest

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

redis:
  global:
    security:
      allowInsecureImages: true  # bitnamilegacy

  fullnameOverride: redis-authentik

  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: bitnamilegacy/redis
    tag: 8.2.1-debian-12-r0

  architecture: standalone

  auth:
    enabled: false

  master:
    revisionHistoryLimit: 2
    priorityClassName: redis-authentik

  metrics:
    enabled: true
    image:
      registry: ghcr.io/flamingo-stack/registry
      repository: bitnamilegacy/redis-exporter
      tag: 1.76.0-debian-12-r0
    podAnnotations:
      loki.grafana.com/scrape: "true"
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
      prometheus.io/path: "/metrics"
