global:
  image:
    tag: dev

registerJob:
  enabled: true
  image:
    registry: ghcr.io/flamingo-stack/registry
    repository: curlimages/curl
    tag: "8.9.1"

initImage:
  registry: ghcr.io/flamingo-stack/registry
  repository: curlimages/curl
  tag: "8.9.1"

image:
  registry: ghcr.io/flamingo-stack/openframe-oss-tenant
  repository: openframe-api
  tag: ""

resources:
  requests:
    cpu: "350m"
    memory: "512Mi"
  limits:
    cpu: "650m"
    memory: "1Gi"

podAnnotations:
  loki.grafana.com/scrape: "true"
  prometheus.io/scrape: "true"
