name: Generate Changes

on:
  workflow_call:
    outputs:
      openframe-api: 
        value: ${{ jobs.changes.outputs.openframe-api }}
      openframe-authorization-server: 
        value: ${{ jobs.changes.outputs.openframe-authorization-server }}
      openframe-external-api: 
        value: ${{ jobs.changes.outputs.openframe-external-api }}
      openframe-client: 
        value: ${{ jobs.changes.outputs.openframe-client }}
      openframe-config: 
        value: ${{ jobs.changes.outputs.openframe-config }}
      openframe-gateway: 
        value: ${{ jobs.changes.outputs.openframe-gateway }}
      openframe-management: 
        value: ${{ jobs.changes.outputs.openframe-management }}
      openframe-stream: 
        value: ${{ jobs.changes.outputs.openframe-stream }}
      openframe-test:
        value: ${{ jobs.changes.outputs.openframe-test }}
      openframe-frontend:
        value: ${{ jobs.changes.outputs.openframe-frontend }}
      client:
        value: ${{ jobs.changes.outputs.client }}
      openframe-client-updater:
        value: ${{ jobs.changes.outputs.openframe-client-updater }}
      openframe-chat:
        value: ${{ jobs.changes.outputs.openframe-chat }}
      helm:
        value: ${{ jobs.changes.outputs.helm }}
      timestamp:
        value: ${{ jobs.changes.outputs.timestamp }}
      timestamp_tag: 
        value: ${{ jobs.changes.outputs.timestamp_tag }}
      commit_sha: 
        value: ${{ jobs.changes.outputs.commit_sha }}
      test_commit_sha: 
        value: ${{ jobs.changes.outputs.test_commit_sha }}

jobs:
  changes:
    name: Changes check
    runs-on: ubuntu-latest
    outputs:
      openframe-api: ${{ steps.filter.outputs.openframe-api }}
      openframe-authorization-server: ${{ steps.filter.outputs.openframe-authorization-server }}
      openframe-external-api: ${{ steps.filter.outputs.openframe-external-api }}
      openframe-client: ${{ steps.filter.outputs.openframe-client }}
      openframe-config: ${{ steps.filter.outputs.openframe-config }}
      openframe-gateway: ${{ steps.filter.outputs.openframe-gateway }}
      openframe-management: ${{ steps.filter.outputs.openframe-management }}
      openframe-stream: ${{ steps.filter.outputs.openframe-stream }}
      openframe-test: ${{ steps.filter.outputs.openframe-test }}
      openframe-frontend: ${{ steps.filter.outputs.openframe-frontend }}
      openframe-chat: ${{ steps.filter.outputs.openframe-chat }}
      client: ${{ steps.filter.outputs.client }}
      openframe-client-updater: ${{ steps.filter.outputs.openframe-client-updater }}
      helm: ${{ steps.filter.outputs.helm }}
      timestamp: ${{ steps.setup_env.outputs.timestamp }}
      timestamp_tag: ${{ steps.setup_env.outputs.timestamp_tag }}
      commit_sha: ${{ steps.setup_env.outputs.commit_sha }}
      test_commit_sha: ${{ steps.setup_env.outputs.test_commit_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up environment
        id: setup_env
        run: |
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
          echo "timestamp_tag=$(date +%d%m%Y%H%M)" >> $GITHUB_OUTPUT
          echo "commit_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "test_commit_sha=test-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            openframe-api:
              - './pom.xml'
              - './openframe/services/openframe-api/**'
            openframe-authorization-server:
              - './pom.xml'
              - './openframe/services/openframe-authorization-server/**'
            openframe-external-api:
              - './pom.xml'
              - './openframe/services/openframe-external-api/**'
            openframe-client:
              - './pom.xml'
              - './openframe/services/openframe-client/**'
            openframe-config:
              - './pom.xml'
              - './openframe/services/openframe-config/**'
            openframe-gateway:
              - './pom.xml'
              - './openframe/services/openframe-gateway/**'
            openframe-management:
              - './pom.xml'
              - './openframe/services/openframe-management/**'
            openframe-stream:
              - './pom.xml'
              - './openframe/services/openframe-stream/**'
            openframe-test:
              - './pom.xml'
              - './openframe/services/openframe-test/**'
            openframe-frontend:
              - './openframe/services/openframe-frontend/**'
            openframe-chat:
              - './clients/openframe-chat/**'
            client:
              - './clients/openframe-client/**'
            openframe-client-updater:
              - './clients/openframe-client-updater/**'
            helm:
              - './manifests/app-of-apps/**'
