name: Generate Matrix

on:
  workflow_call:
    outputs:
      images_matrix:
        description: "Images Matrix configuration for all components"
        value: ${{ jobs.matrix.outputs.images_matrix }}
      clients_matrix:
        description: "Clients Matrix configuration for all components"
        value: ${{ jobs.matrix.outputs.clients_matrix }}

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      images_matrix: ${{ steps.matrix.outputs.images_matrix }}
      clients_matrix: ${{ steps.matrix.outputs.clients_matrix }}
    steps:
      - name: Define Matrix
        id: matrix
        run: |
          images_matrix_json='[
            {
              "name": "openframe-api",
              "path": "./openframe/services/openframe-api",
              "context": "."
            },
            {
              "name": "openframe-authorization-server",
              "path": "./openframe/services/openframe-authorization-server",
              "context": "."
            },
            {
              "name": "openframe-external-api",
              "path": "./openframe/services/openframe-external-api",
              "context": "."
            },
            {
              "name": "openframe-client",
              "path": "./openframe/services/openframe-client",
              "context": "."
            },
            {
              "name": "openframe-config",
              "path": "./openframe/services/openframe-config",
              "context": "."
            },
            {
              "name": "openframe-gateway",
              "path": "./openframe/services/openframe-gateway",
              "context": "."
            },
            {
              "name": "openframe-management",
              "path": "./openframe/services/openframe-management",
              "context": "."
            },
            {
              "name": "openframe-stream",
              "path": "./openframe/services/openframe-stream",
              "context": "."
            },
            {
              "name": "openframe-frontend",
              "path": "./openframe/services/openframe-frontend"
            }
          ]'
          clients_matrix_json='[
            {  
              "id": "client",
              "name": "openframe-client",
              "path": "./clients/openframe-client",
              "os": "macos",
              "target": "aarch64-apple-darwin,x86_64-apple-darwin",
              "target_path": "./clients/openframe-client/target"
            },
            {
              "id": "client",
              "name": "openframe-client",
              "path": "./clients/openframe-client",
              "os": "windows",
              "target": "x86_64-pc-windows-msvc",
              "target_path": "./clients/openframe-client/target"
            },
            {
              "name": "openframe-chat",
              "path": "./clients/openframe-chat",
              "os": "macos-26",
              "target": "universal-apple-darwin",
              "archs": "aarch64-apple-darwin,x86_64-apple-darwin",
              "target_path": "./clients/openframe-chat/src-tauri/target"
            },
            {
              "name": "openframe-chat",
              "path": "./clients/openframe-chat",
              "os": "windows",
              "target": "x86_64-pc-windows-msvc",
              "target_path": "./clients/openframe-chat/src-tauri/target"
            }
          ]'

          # Write the matrix to the output
          {
            echo 'images_matrix<<EOF'
            echo "$images_matrix_json"
            echo EOF
            echo 'clients_matrix<<EOF'
            echo "$clients_matrix_json"
            echo EOF
          } >> $GITHUB_OUTPUT
